// Code generated by MockGen. DO NOT EDIT.
// Source: ../../app/tokenizer/tokenizer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tokenizer "github.com/Turalchik/pvz-service/internal/app/tokenizer"
	gomock "github.com/golang/mock/gomock"
)

// MockTokenizerInterface is a mock of TokenizerInterface interface.
type MockTokenizerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenizerInterfaceMockRecorder
}

// MockTokenizerInterfaceMockRecorder is the mock recorder for MockTokenizerInterface.
type MockTokenizerInterfaceMockRecorder struct {
	mock *MockTokenizerInterface
}

// NewMockTokenizerInterface creates a new mock instance.
func NewMockTokenizerInterface(ctrl *gomock.Controller) *MockTokenizerInterface {
	mock := &MockTokenizerInterface{ctrl: ctrl}
	mock.recorder = &MockTokenizerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenizerInterface) EXPECT() *MockTokenizerInterfaceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockTokenizerInterface) GenerateToken(userID, role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", userID, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockTokenizerInterfaceMockRecorder) GenerateToken(userID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTokenizerInterface)(nil).GenerateToken), userID, role)
}

// VerifyToken mocks base method.
func (m *MockTokenizerInterface) VerifyToken(tokenString string) (*tokenizer.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", tokenString)
	ret0, _ := ret[0].(*tokenizer.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockTokenizerInterfaceMockRecorder) VerifyToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockTokenizerInterface)(nil).VerifyToken), tokenString)
}
